version: "3"
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    container_name: secrets_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 32781:5432

  server:
    build: .
    ports:
      - 44044:8888
    environment:
      - APP_PORT=:8888
    network_mode: host
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "19090:9090"

volumes:
  postgres_data:

