version: "3"
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    container_name: secrets_db
    environment:
      - POSTGRES_USER=bekarys
      - POSTGRES_PASSWORD=mynewpassword
      - POSTGRES_DB=secrets
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432
    networks:
      - base

  server:
    build: .
    ports:
      - 88:8888
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - base

# Networks to be created to facilitate communication between containers
networks:
  base:
    driver: bridge

volumes:
  postgres_data:
  cache:

